# Generated by Django 5.1.7 on 2025-03-22 14:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('año_lanzamiento', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Año de lanzamiento')),
                ('genero', models.CharField(choices=[('ACC', 'Acción'), ('COM', 'Comedia'), ('DRA', 'Drama'), ('SCI', 'Ciencia Ficción'), ('TER', 'Terror'), ('ANI', 'Animación'), ('AVT', 'Aventura'), ('FAN', 'Fantasía'), ('ROM', 'Romance'), ('DOC', 'Documental')], max_length=3, verbose_name='Género')),
                ('duracion', models.PositiveIntegerField(help_text='Duración en minutos', verbose_name='Duración (minutos)')),
                ('calificacion', models.FloatField(help_text='Calificación entre 0.0 y 10.0', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Calificación')),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='peliculas/portadas/', verbose_name='Imagen de portada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'Películas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
